name: sunat_cpe_dart
description: Librería Dart para la construcción, validación y emisión de Comprobantes de Pago Electrónico (CPE) conforme a los estándares UBL y normativas SUNAT.
version: 0.1.0
homepage: https://github.com/Cesarius1970/sunat_cpe_dart
repository: https://github.com/Cesarius1970/sunat_cpe_dart
issue_tracker: https://github.com/Cesarius1970/sunat_cpe_dart/issues
documentation: https://github.com/Cesarius1970/sunat_cpe_dart/tree/main/doc

topics:
  - sunat
  - cpe
  - facturacion-electronica
  - ubl
  - peru

environment:
  sdk: ^3.13.4

dependencies:
  archive: ^4.3.0
  crypto: ^3.0.7
  decimal: ^3.2.6
  http: ^1.6.0
  xml: ^7.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
